### PR TITLE
Update package.json

### LINKED ISSUE #5: Error: Cannot find module @2toad/diff-match-patch/diff_match_patch.js
Thanks for reporting the below issue @frankkienl:

## Error

```
node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module '/Users/frankbouwens/priv/SOME_PROJECT/node_modules/@2toad/diff-match-patch/diff_match_patch.js'. Please verify that the package.json has a valid "main" entry
```

## Environment

node: v16.14.2 
npm: 8.5.0

## RCA

Per @frankkienl :

> I noticed that the file: diff-match-patch.js is named "diff-match-patch.js"  with `-`'s and the file: package.json#L12 mentions that same file, but with `_` instead of `-`.

### PR DESCRIPTION
**Pull request by frankkienl**
Fixes #5:

```
node:internal/modules/cjs/loader:361
      throw err;
      ^

Error: Cannot find module '/Users/frankbouwens/priv/SOME_PROJECT/node_modules/@2toad/diff-match-patch/diff_match_patch.js'. Please verify that the package.json has a valid "main" entry
```

### CODE REVIEW

**Comment by JasonPierce** [comment]
Thanks for the PR Frank. Will you please send me the Node and NPM versions you are using so I can reproduce and test this?

**Comment by frankkienl** [comment]
Hi Jason, 

Here are my node and npm versions:
```
node: v16.14.2 
npm: 8.5.0
```

I noticed that the file:
https://github.com/2Toad/diff-match-patch/blob/400fc9962afa78df9d55a12b1ba1e2df31f3cf80/diff-match-patch.js
is named "diff-match-patch.js"  with `-`'s
and the file: 
https://github.com/2Toad/diff-match-patch/blob/400fc9962afa78df9d55a12b1ba1e2df31f3cf80/package.json#L12  
mentions that same file, but with `_` instead of `-`.
When I changed the package.json file as in this PR, the error disappeared.

Hope this helps!

**Comment by JasonPierce** [comment]
Thanks Frank!

Will you pleas merge latest `master` into your branch? I've replaced the defunct Travis CI build script with new GitHub Actions, which will test your changes against the supported Node versions

**Comment by frankkienl** [comment]
Fetched changes from upstream. Master should be merged now ;-) !

**Pull request merged**
